# Generated by Django 2.0.7 on 2020-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocr_img', models.TextField(default='', verbose_name='base64')),
                ('ocr_key', models.TextField(default='', verbose_name='图片中的关键字')),
            ],
        ),
    ]
